<?php $errors = $_SESSION['purchase_errors'] ?? []; unset($_SESSION['purchase_errors']); ?>
<?php if ($errors): ?><div class="alert error"><ul style="margin:0;padding-left:18px"><?php foreach ($errors as $er): ?><li><?= e($er) ?></li><?php endforeach ?></ul></div><?php endif ?>
<?php if (!$canReceive): ?><div class="alert info"><?= e(__('Ricezione automatica via PEC non configurata: carica a mano i file XML (o P7M, o uno ZIP) scaricati dal cassetto fiscale.')) ?> <a href="<?= e(url('admin/einvoice/setup?step=2')) ?>"><?= e(__('Configura la PEC')) ?></a></div><?php endif ?>
<div class="grid2"><div>
<div class="toolbar"><form method="get" action="<?= e(url('admin/purchases')) ?>"><input type="search" name="q" placeholder="<?= e(__('Fornitore, numero, P.IVA')) ?>" value="<?= e($_GET['q'] ?? '') ?>"><select name="paid"><option value=""><?= e(__('Tutte')) ?></option><option value="0" <?= ($_GET['paid'] ?? '') === '0' ? 'selected' : '' ?>><?= e(__('Da pagare')) ?></option><option value="1" <?= ($_GET['paid'] ?? '') === '1' ? 'selected' : '' ?>><?= e(__('Pagate')) ?></option></select><button class="btn sec"><?= e(__('Filtra')) ?></button></form></div>
<div class="card" style="padding:0"><table><thead><tr><th><?= e(__('Data')) ?></th><th><?= e(__('Fornitore')) ?></th><th><?= e(__('Numero')) ?></th><th class="right"><?= e(__('Totale')) ?></th><th><?= e(__('Stato')) ?></th></tr></thead><tbody>
<?php foreach ($rows as $r): $neg = in_array($r['doc_type'], Alien\Services\Purchases::CREDIT_TYPES, true); ?><tr><td><?= e($r['issue_date']) ?></td><td><a href="<?= e(url('admin/purchases/' . $r['id'])) ?>"><strong><?= e($r['supplier_name']) ?></strong></a><div class="muted"><?= e($r['supplier_vat']) ?></div></td><td><?= e($r['number']) ?> <span class="muted"><?= e($r['doc_type']) ?></span></td>
<td class="right"><?= $neg ? '−' : '' ?><?= e(Alien\Core\Money::format((int)$r['total'], $r['currency'])) ?></td><td><?= $r['paid_at'] ? '<span class="pill ok">' . e(__('Pagata')) . '</span>' : ($r['due_date'] && $r['due_date'] < date('Y-m-d') ? '<span class="pill bad">' . e(__('Scaduta')) . '</span>' : '<span class="pill warn">' . e(__('Da pagare')) . '</span>') ?></td></tr><?php endforeach ?>
<?php if (!$rows): ?><tr><td colspan="5"><?= a_empty('📥', __('Nessuna fattura ricevuta'), __('Le fatture dei fornitori compariranno qui, in automatico dalla PEC o caricandole a mano.')) ?></td></tr><?php endif ?></tbody></table></div></div>
<div class="card"><h2><?= e(__('Carica fatture')) ?></h2><form method="post" enctype="multipart/form-data" action="<?= e(url('admin/purchases/upload')) ?>"><?= csrf_field() ?>
<div class="field"><input type="file" name="files[]" accept=".xml,.p7m,.zip" multiple required></div><p class="help"><?= e(__('Accetta XML, P7M firmati e ZIP con più fatture. I duplicati vengono ignorati.')) ?></p><button class="btn" type="submit">⬆ <?= e(__('Importa')) ?></button></form></div></div>
