<?php $cur = $p['currency']; $f = static fn($c) => Alien\Core\Money::format((int)$c, $cur); $neg = in_array($p['doc_type'], Alien\Services\Purchases::CREDIT_TYPES, true); ?>
<div class="grid2"><div>
<div class="card"><div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><div><h2 style="margin:0"><?= e($p['supplier_name']) ?></h2><div class="muted"><?= e($d['supplier']['vat'] ?? '') ?> <?= e($d['supplier']['address'] ?? '') ?> <?= e(($d['supplier']['cap'] ?? '') . ' ' . ($d['supplier']['city'] ?? '')) ?></div></div>
  <div style="text-align:right"><strong><?= e(Alien\EInvoice\Fiscal::DOC_TYPES[$p['doc_type']] ?? $p['doc_type']) ?> <?= e($p['number']) ?></strong><div class="muted"><?= e($p['issue_date']) ?></div></div></div>
<?php if (!empty($d['causale'])): ?><p class="muted"><?= e($d['causale']) ?></p><?php endif ?>
<table style="margin-top:12px"><thead><tr><th><?= e(__('Descrizione')) ?></th><th class="right"><?= e(__('Qtà')) ?></th><th class="right"><?= e(__('Prezzo')) ?></th><th class="right"><?= e(__('Importo')) ?></th><th class="right"><?= e(__('IVA %')) ?></th></tr></thead><tbody>
<?php foreach ($d['lines'] ?? [] as $l): ?><tr><td><?= e($l['desc']) ?></td><td class="right"><?= e(rtrim(rtrim(number_format($l['qty'], 2, ',', ''), '0'), ',')) ?></td><td class="right"><?= e($f($l['unit'])) ?></td><td class="right"><?= e($f($l['total'])) ?></td><td class="right"><?= e(rtrim(rtrim(number_format($l['rate'], 2, ',', ''), '0'), ',')) ?></td></tr><?php endforeach ?></tbody></table>
<table style="margin-top:12px;max-width:380px;margin-left:auto"><tbody><?php foreach ($d['summary'] ?? [] as $s): ?><tr><td class="muted"><?= e(__('Imponibile %s%%', rtrim(rtrim(number_format($s['rate'], 2, ',', ''), '0'), ','))) ?><?= $s['nature'] ? ' ' . e($s['nature']) : '' ?></td><td class="right"><?= e($f($s['net'])) ?></td><td class="right"><?= e(__('IVA')) ?> <?= e($f($s['vat'])) ?></td></tr><?php endforeach ?>
<tr><td colspan="2" class="right"><strong><?= e(__('Totale')) ?></strong></td><td class="right"><strong><?= $neg ? '−' : '' ?><?= e($f($p['total'])) ?></strong></td></tr></tbody></table>
<?php if (!empty($d['payments'])): ?><p class="muted" style="margin-top:12px"><?= e(__('Pagamento')) ?>: <?php foreach ($d['payments'] as $pm): ?><?= e((Alien\EInvoice\Fiscal::PAYMENT_MODES[$pm['mode']] ?? $pm['mode']) . ($pm['due'] ? ' — ' . $pm['due'] : '') . ' — ' . $f($pm['amount']) . ($pm['iban'] ? ' — ' . $pm['iban'] : '')) ?>; <?php endforeach ?></p><?php endif ?></div></div>
<div><div class="card"><h2><?= e(__('Registrazione')) ?></h2><form method="post" action="<?= e(url('admin/purchases/' . $p['id'])) ?>"><?= csrf_field() ?>
<div class="field"><label for="f_category"><?= e(__('Categoria di costo')) ?></label><input id="f_category" name="category" list="cats" value="<?= e($p['category']) ?>" placeholder="<?= e(__('es. Merce, Trasporti, Software')) ?>"><datalist id="cats"><?php foreach ($categories as $c): ?><option value="<?= e($c) ?>"><?php endforeach ?></datalist></div>
<?= a_input('deductible', __('IVA detraibile (%)'), $p['deductible'], 'number', ['min' => 0, 'max' => 100]) ?>
<?= a_input('paid_at', __('Pagata il'), $p['paid_at'] ?? '', 'date', [], __('Vuoto = ancora da pagare.')) ?>
<?= a_textarea('notes', __('Note'), $p['notes'] ?? '', 3) ?>
<button class="btn" type="submit"><?= e(__('Salva')) ?></button> <a class="btn sec" href="<?= e(url('admin/purchases/' . $p['id'] . '/xml')) ?>">⬇ XML</a></form>
<form method="post" action="<?= e(url('admin/purchases/' . $p['id'])) ?>" data-confirm="<?= e(__('Eliminare la fattura?')) ?>" style="margin-top:10px"><?= csrf_field() ?><input type="hidden" name="action" value="delete"><button class="btn danger sm"><?= e(__('Elimina')) ?></button></form></div></div></div>
