<?php if (!$configured): ?><div class="alert info"><?= e(__('Prima di emettere fatture completa la procedura guidata.')) ?> <a class="btn sm" href="<?= e(url('admin/einvoice/setup')) ?>"><?= e(__('Configura ora')) ?></a></div><?php endif ?>
<div class="status-tabs"><a class="<?= $status === '' ? 'on' : '' ?>" href="<?= e(url('admin/einvoice')) ?>"><?= e(__('Tutte')) ?><b><?= (int)$counts[''] ?></b></a>
<?php foreach (Alien\Services\EInvoices::STATUSES as $k => $l): if (empty($counts[$k])) { continue; } ?><a class="<?= $status === $k ? 'on' : '' ?>" href="<?= e(url('admin/einvoice?status=' . $k)) ?>"><?= e(__($l)) ?><b><?= (int)$counts[$k] ?></b></a><?php endforeach ?>
<a class="btn sec sm" style="margin-left:auto" href="<?= e(url('admin/einvoice/setup')) ?>">⚙ <?= e(__('Impostazioni')) ?></a></div>
<?php if ($lastSync): ?><p class="muted" style="font-size:.85rem"><?= e(__('Ultima sincronizzazione PEC: %s', a_dt($lastSync))) ?><?= !empty($report['errors']) ? ' — <span style="color:var(--bad)">' . e(implode(' | ', $report['errors'])) . '</span>' : '' ?></p><?php endif ?>
<div class="card" style="padding:0"><table><thead><tr><th><?= e(__('Numero')) ?></th><th><?= e(__('Data')) ?></th><th><?= e(__('Cliente')) ?></th><th><?= e(__('Stato')) ?></th><th class="right"><?= e(__('Totale')) ?></th><th></th></tr></thead><tbody>
<?php foreach ($rows as $r): ?><tr><td><a href="<?= e(url('admin/einvoice/' . $r['id'])) ?>"><strong><?= e($r['number']) ?></strong></a> <span class="muted"><?= e($r['doc_type']) ?></span></td><td><?= e($r['issue_date']) ?></td><td><?= e($r['customer_name']) ?></td>
<td><span class="pill <?= in_array($r['status'], ['delivered', 'accepted', 'expired'], true) ? 'ok' : (in_array($r['status'], ['rejected', 'error', 'refused'], true) ? 'bad' : 'warn') ?>"><?= e(Alien\Services\EInvoices::statusLabel($r['status'])) ?></span></td>
<td class="right"><?= e(Alien\Core\Money::format((int)$r['total'], $r['currency'])) ?></td><td class="right"><a class="btn sec sm" href="<?= e(url('admin/einvoice/' . $r['id'] . '/xml')) ?>">XML</a></td></tr><?php endforeach ?>
<?php if (!$rows): ?><tr><td colspan="6"><?= a_empty('🧾', __('Nessuna fattura elettronica'), __('Apri un ordine e scegli "Emetti fattura elettronica", oppure attiva l\'emissione automatica nelle impostazioni.')) ?></td></tr><?php endif ?></tbody></table></div>
