<?php $errors = json_decode((string)$inv['errors'], true) ?: []; $isCredit = $inv['doc_type'] === 'TD04'; ?>
<div class="grid2"><div>
<div class="card"><h2><?= e($isCredit ? __('Nota di credito') : __('Fattura')) ?> <?= e($inv['number']) ?> <span class="muted"><?= e($inv['doc_type']) ?></span></h2>
<p><span class="pill <?= in_array($inv['status'], ['delivered', 'accepted', 'expired'], true) ? 'ok' : (in_array($inv['status'], ['rejected', 'error', 'refused'], true) ? 'bad' : 'warn') ?>"><?= e(Alien\Services\EInvoices::statusLabel($inv['status'])) ?></span></p>
<table><tbody><tr><td class="muted"><?= e(__('Data')) ?></td><td><?= e($inv['issue_date']) ?></td></tr><tr><td class="muted"><?= e(__('Cliente')) ?></td><td><?= e($inv['customer_name']) ?> <span class="muted"><?= e($inv['customer_vat'] ?: $inv['customer_cf']) ?></span></td></tr>
<tr><td class="muted"><?= e(__('Imponibile / IVA / Totale')) ?></td><td><?= e(Alien\Core\Money::format((int)$inv['net'], $inv['currency'])) ?> / <?= e(Alien\Core\Money::format((int)$inv['vat'], $inv['currency'])) ?> / <strong><?= e(Alien\Core\Money::format((int)$inv['total'], $inv['currency'])) ?></strong></td></tr>
<tr><td class="muted"><?= e(__('File')) ?></td><td><code><?= e($inv['file_name']) ?></code></td></tr><?php if ($inv['sdi_id']): ?><tr><td class="muted"><?= e(__('Identificativo SdI')) ?></td><td><?= e($inv['sdi_id']) ?></td></tr><?php endif ?>
<?php if ($order): ?><tr><td class="muted"><?= e(__('Ordine')) ?></td><td><a href="<?= e(url('admin/orders/' . $order['id'])) ?>"><?= e($order['number']) ?></a></td></tr><?php endif ?></tbody></table></div>
<?php if ($errors): ?><div class="alert error"><strong><?= e(__('Errori')) ?></strong><ul style="margin:6px 0 0;padding-left:18px"><?php foreach ($errors as $err): ?><li><?= e($err) ?></li><?php endforeach ?></ul></div><?php endif ?>
<div class="card"><h2><?= e(__('Cronologia')) ?></h2><pre style="white-space:pre-wrap;margin:0;font:inherit;font-size:.88rem"><?= e($inv['log']) ?></pre></div></div>
<div><div class="card"><h2><?= e(__('Azioni')) ?></h2><div style="display:grid;gap:8px">
<a class="btn sec" href="<?= e(url('admin/einvoice/' . $inv['id'] . '/xml')) ?>">⬇ <?= e(__('Scarica XML')) ?></a>
<?php if ($order): ?><a class="btn sec" href="<?= e(url('admin/einvoice/' . $inv['id'] . '/pdf')) ?>">⬇ <?= e(__('Copia di cortesia PDF')) ?></a><?php endif ?>
<?php if (in_array($inv['status'], ['generated'], true)): ?><?php if ($canSend): ?><form method="post" action="<?= e(url('admin/einvoice/' . $inv['id'])) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="send"><button class="btn" style="width:100%">📤 <?= e(__('Invia a SdI via PEC')) ?></button></form>
<?php else: ?><div class="alert info" style="margin:0"><?= e(__('Invio via PEC non configurato: scarica l\'XML e caricalo sul portale "Fatture e Corrispettivi" dell\'Agenzia delle Entrate o sul tuo provider, poi segna la fattura come inviata.')) ?></div>
<form method="post" action="<?= e(url('admin/einvoice/' . $inv['id'])) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="status" value="sent"><button class="btn sec" style="width:100%"><?= e(__('Segna come inviata')) ?></button></form><?php endif ?><?php endif ?>
<?php if (in_array($inv['status'], ['rejected', 'error'], true) && !$isCredit): ?><form method="post" action="<?= e(url('admin/einvoice/' . $inv['id'])) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="regenerate"><button class="btn" style="width:100%">🔁 <?= e(__('Correggi e rigenera')) ?></button></form>
<p class="muted" style="font-size:.82rem;margin:0"><?= e(__('Una fattura scartata si può reinviare con lo stesso numero entro 5 giorni dallo scarto.')) ?></p><?php endif ?>
<?php if (!$isCredit && in_array($inv['status'], Alien\Services\EInvoices::VALID, true)): ?><form method="post" action="<?= e(url('admin/einvoice/' . $inv['id'])) ?>" data-confirm="<?= e(__('Emettere una nota di credito per l\'intero importo?')) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="credit"><button class="btn danger" style="width:100%"><?= e(__('Emetti nota di credito')) ?></button></form><?php endif ?>
</div></div></div></div>
